controllers:
    resource: ../src/Controller/
    type: attribute

#index:
#    path: /
#    # the controller value has the format 'controller_class::method_name'
#    controller: App\Controller\ArticleController::homepage
